//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace SAP_BO_4._2_Web_API_client {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class dataprovider {
        
        private string idField;
        
        private string nameField;
        
        private ushort dataSourceIdField;
        
        private string dataSourceCuidField;
        
        private string dataSourcePrefixField;
        
        private string dataSourceTypeField;
        
        private System.DateTime updatedField;
        
        private byte durationField;
        
        private bool isPartialField;
        
        private ushort rowCountField;
        
        private byte flowCountField;
        
        private dataproviderExpression[] dictionaryField;
        
        private dataproviderProperty[] propertiesField;
        
        private bool refreshableField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public ushort dataSourceId {
            get {
                return this.dataSourceIdField;
            }
            set {
                this.dataSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public string dataSourceCuid {
            get {
                return this.dataSourceCuidField;
            }
            set {
                this.dataSourceCuidField = value;
            }
        }
        
        /// <remarks/>
        public string dataSourcePrefix {
            get {
                return this.dataSourcePrefixField;
            }
            set {
                this.dataSourcePrefixField = value;
            }
        }
        
        /// <remarks/>
        public string dataSourceType {
            get {
                return this.dataSourceTypeField;
            }
            set {
                this.dataSourceTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public byte duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public bool isPartial {
            get {
                return this.isPartialField;
            }
            set {
                this.isPartialField = value;
            }
        }
        
        /// <remarks/>
        public ushort rowCount {
            get {
                return this.rowCountField;
            }
            set {
                this.rowCountField = value;
            }
        }
        
        /// <remarks/>
        public byte flowCount {
            get {
                return this.flowCountField;
            }
            set {
                this.flowCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("expression", IsNullable=false)]
        public dataproviderExpression[] dictionary {
            get {
                return this.dictionaryField;
            }
            set {
                this.dictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public dataproviderProperty[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool refreshable {
            get {
                return this.refreshableField;
            }
            set {
                this.refreshableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataproviderExpression {
        
        private string idField;
        
        private string nameField;
        
        private string dataSourceObjectIdField;
        
        private string formulaLanguageIdField;
        
        private string aggregationFunctionField;
        
        private string dataTypeField;
        
        private string qualificationField;
        
        private bool highPrecisionField;
        
        private bool highPrecisionFieldSpecified;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string dataSourceObjectId {
            get {
                return this.dataSourceObjectIdField;
            }
            set {
                this.dataSourceObjectIdField = value;
            }
        }
        
        /// <remarks/>
        public string formulaLanguageId {
            get {
                return this.formulaLanguageIdField;
            }
            set {
                this.formulaLanguageIdField = value;
            }
        }
        
        /// <remarks/>
        public string aggregationFunction {
            get {
                return this.aggregationFunctionField;
            }
            set {
                this.aggregationFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qualification {
            get {
                return this.qualificationField;
            }
            set {
                this.qualificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool highPrecision {
            get {
                return this.highPrecisionField;
            }
            set {
                this.highPrecisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highPrecisionSpecified {
            get {
                return this.highPrecisionFieldSpecified;
            }
            set {
                this.highPrecisionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataproviderProperty {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
